import { useCallback,useEffect,useState } from 'react'; import { CheckCircle2,ChevronDown,Clock3,ListTodo,LogOut,Menu,Plus,Search,TimerReset,XCircle } from 'lucide-react'; import { toast } from 'sonner';
import { api } from '../lib/api'; import type { Priority,Status,Summary,Task,TaskInput } from '../types'; import { useAuth } from '../context/AuthContext'; import { TaskCard } from './TaskCard'; import { TaskModal } from './TaskModal';
const empty:Summary={total:0,pending:0,inProgress:0,completed:0,overdue:0};
export function Dashboard(){
 const{user,logout}=useAuth();const[tasks,setTasks]=useState<Task[]>([]),[summary,setSummary]=useState(empty),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[status,setStatus]=useState<Status|''>(''),[priority,setPriority]=useState<Priority|''>(''),[sort,setSort]=useState('newest'),[modal,setModal]=useState(false),[editing,setEditing]=useState<Task|null>(null),[mobileNav,setMobileNav]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const params=new URLSearchParams();if(search)params.set('search',search);if(status)params.set('status',status);if(priority)params.set('priority',priority);params.set('sort',sort);const[data,counts]=await Promise.all([api.tasks('?'+params),api.summary()]);setTasks(data.tasks);setSummary(counts.summary);}catch(e){toast.error(e instanceof Error?e.message:'Could not load tasks.')}finally{setLoading(false)}},[search,status,priority,sort]);
 useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[load]);
 const save=async(input:TaskInput)=>{if(editing){await api.update(editing.id,input);toast.success('Task updated');}else{await api.create(input);toast.success('Task added');}setModal(false);setEditing(null);await load();};
 const remove=async(task:Task)=>{if(!confirm('Delete “'+task.title+'”? This cannot be undone.'))return;await api.remove(task.id);toast.success('Task deleted');await load();};
 const cards=[['All tasks',summary.total,ListTodo,'ink'],['Pending',summary.pending,Clock3,'amber'],['In progress',summary.inProgress,TimerReset,'blue'],['Completed',summary.completed,CheckCircle2,'green'],['Overdue',summary.overdue,XCircle,'red']] as const;
 const first=user?.name.split(' ')[0]||'there'; const date=new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date());
 return <div className="app-shell"><aside className={mobileNav?'sidebar open':'sidebar'}><div className="brand"><span className="brand-mark">D</span> daymark</div><button className="mobile-close" onClick={()=>setMobileNav(false)}>×</button><nav><p>WORKSPACE</p><a className="active"><ListTodo/>My tasks</a></nav><div className="sidebar-foot"><div className="avatar">{first[0]}</div><div><b>{user?.name}</b><small>{user?.email}</small></div><button className="icon-button" onClick={logout} title="Sign out"><LogOut/></button></div></aside>
 <main className="workspace"><header className="topbar"><button className="mobile-menu" onClick={()=>setMobileNav(true)}><Menu/></button><span>{date}</span><button className="secondary signout" onClick={logout}><LogOut/> Sign out</button></header>
 <div className="content"><section className="welcome"><div><p className="eyebrow">YOUR DAY AT A GLANCE</p><h1>Good {new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}, {first}.</h1><p>Here’s what’s on your plate. One thing at a time.</p></div><button className="primary" onClick={()=>{setEditing(null);setModal(true)}}><Plus/>Add a task</button></section>
 <section className="summary-grid">{cards.map(([label,count,Icon,tone])=><button className={'summary-card '+tone} key={label} onClick={()=>label==='Pending'?setStatus('pending'):label==='In progress'?setStatus('in_progress'):label==='Completed'?setStatus('completed'):label==='All tasks'?setStatus(''):undefined}><span><Icon/></span><div><strong>{count}</strong><small>{label}</small></div></button>)}</section>
 <section className="task-section"><div className="section-title"><div><p className="eyebrow">THE LIST</p><h2>Things to do</h2></div><span>{tasks.length} {tasks.length===1?'task':'tasks'}</span></div>
 <div className="toolbar"><div className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by task title…"/></div><div className="filters"><label>Status<ChevronDown/><select value={status} onChange={e=>setStatus(e.target.value as Status|'')}><option value="">All statuses</option><option value="pending">Pending</option><option value="in_progress">In progress</option><option value="completed">Completed</option></select></label><label>Priority<ChevronDown/><select value={priority} onChange={e=>setPriority(e.target.value as Priority|'')}><option value="">All priorities</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label>Sort<ChevronDown/><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest created</option><option value="oldest">Oldest created</option><option value="due_date">Due date</option></select></label></div></div>
 {loading?<div className="task-grid">{[1,2,3].map(i=><div className="task-card skeleton" key={i}/>)}</div>:tasks.length?<div className="task-grid">{tasks.map(task=><TaskCard key={task.id} task={task} onEdit={()=>{setEditing(task);setModal(true)}} onDelete={()=>remove(task)}/>)}</div>:<div className="empty-state"><div>✓</div><h3>Nothing here right now.</h3><p>Try clearing the filters, or add the next thing on your mind.</p><button className="secondary" onClick={()=>{setSearch('');setStatus('');setPriority('')}}>Clear filters</button></div>}
 </section></div></main>{modal&&<TaskModal task={editing} onClose={()=>{setModal(false);setEditing(null)}} onSave={save}/>}</div>;
}
