import { useEffect, useState, type FormEvent } from 'react';
import { BellRing, X } from 'lucide-react';
import type { Task, TaskInput } from '../types';
const today = () => new Date().toLocaleDateString('en-CA');
const blank = (): TaskInput => ({ title: '', description: '', priority: 'medium', status: 'pending', dueDate: today(), reminderDaysBefore: 1 });
export function TaskModal({ task, onClose, onSave }: { task: Task | null; onClose: () => void; onSave: (value: TaskInput) => Promise<void> }) {
  const [value, setValue] = useState<TaskInput>(blank()); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { if (task) setValue({ title: task.title, description: task.description || '', priority: task.priority, status: task.status, dueDate: task.dueDate, reminderDaysBefore: task.reminderDaysBefore }); }, [task]);
  const update = <K extends keyof TaskInput>(key: K, next: TaskInput[K]) => setValue((current) => ({ ...current, [key]: next }));
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); if (!value.title.trim()) { setError('Give this task a title.'); return; } if (value.dueDate < today()) { setError('Due date cannot be earlier than today.'); return; } setBusy(true); try { await onSave(value); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save this task.'); setBusy(false); } };
  const reminderText = value.reminderDaysBefore === null ? 'This task will not send a reminder.' : value.reminderDaysBefore === 0 ? 'You will be reminded on the due date.' : 'You will be reminded ' + value.reminderDaysBefore + ' ' + (value.reminderDaysBefore === 1 ? 'day' : 'days') + ' early.';
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><form className="task-modal" onSubmit={submit}>
    <div className="modal-head"><div><p className="eyebrow">{task ? 'EDIT TASK' : 'NEW TASK'}</p><h2>{task ? 'Make a few changes.' : 'What needs doing?'}</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close task form"><X /></button></div>
    <label>Task title<input value={value.title} onChange={(event) => update('title', event.target.value)} placeholder="e.g. Send the final proposal" maxLength={150} autoFocus required /></label>
    <label>Notes <span className="optional">optional</span><textarea value={value.description} onChange={(event) => update('description', event.target.value)} placeholder="Add a little context…" rows={4} maxLength={2000} /></label>
    <div className="field-row"><label>Priority<select value={value.priority} onChange={(event) => update('priority', event.target.value as TaskInput['priority'])}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label>Status<select value={value.status} onChange={(event) => update('status', event.target.value as TaskInput['status'])}><option value="pending">Pending</option><option value="in_progress">In progress</option><option value="completed">Completed</option></select></label></div>
    <div className="field-row due-reminder-row"><label>Due date<input type="date" min={today()} value={value.dueDate} onChange={(event) => update('dueDate', event.target.value)} required /></label><label>Reminder<div className="select-with-icon"><BellRing /><select value={value.reminderDaysBefore === null ? 'off' : String(value.reminderDaysBefore)} onChange={(event) => update('reminderDaysBefore', event.target.value === 'off' ? null : Number(event.target.value))}><option value="0">On the due date</option><option value="1">1 day before (default)</option><option value="2">2 days before</option><option value="3">3 days before</option><option value="7">1 week before</option><option value="off">No reminder</option></select></div></label></div>
    <p className="reminder-help">{reminderText}</p>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy ? 'Saving…' : task ? 'Save changes' : 'Add task'}</button></div>
  </form></div>;
}
